### PR TITLE
French Translation by Myuui

### PR DESCRIPTION
**Pull request by Myuui**

### CODE REVIEW

**Comment by Qendolin** [comment]
I've just pushed an update.
- `betterclouds.message.disable` has been renamed to `betterclouds.message.generic.disable`
- `betterclouds.message.generic.error` was added
You don't have to translate the `betterclouds.message.renderdoc.*` strings

**Comment by Myuui** [comment]
Updated, please review again.

> I've just pushed an update.
> 
> * `betterclouds.message.disable` has been renamed to `betterclouds.message.generic.disable`
> * `betterclouds.message.generic.error` was added
>   You don't have to translate the `betterclouds.message.renderdoc.*` strings

**Comment by Qendolin** [comment]
Thanks!

**Comment by Qendolin** [comment]
I've published it for all 1.20.* versions

**Comment by Myuui** [comment]
Thanks.

**Comment by Myuui** [comment]
btw https://github.com/Qendolin/better-clouds/blob/main/Contributions.md

**Comment by Qendolin** [comment]
Sorry! I totally forgot

**Pull request merged**
