### PR TITLE
i18n: Add Simplified Chinese language support

### PR DESCRIPTION
**Pull request by Cccc-owo**

### CODE REVIEW

**Comment by Qendolin** [comment]
I'll merge it into the next release. (If I remember to)

**Comment by Qendolin** [comment]
Hey, if you update the translations I'll merge it for 1.19.4

**Comment by Cccc-owo** [comment]
> Hey, if you update the translations now I'll merge them for 1.19.4

Sure, just wait a minute : )

**Comment by Cccc-owo** [comment]
Later I'll open a PR again.

**Pull request closed without merging**
