### PR TITLE
Added Traditional Chinese (zh_tw.json)

### PR DESCRIPTION
**Pull request by yichifauzi**
Added Traditional Chinese translations

### CODE REVIEW

**Comment by Qendolin** [comment]
Since I have just released new versions this will have to wait quite a while until the next release

**Comment by Qendolin** [comment]
Hey, I'll be adding one more message in the next release (betterclouds.message.hwMaybeIncompatible) can you translate that as well? Then I can merge it

**Comment by yichifauzi** [comment]
Yeah sure

**Comment by yichifauzi** [comment]
> Hey, I'll be adding one more message in the next release (betterclouds.message.hwMaybeIncompatible) can you please translate that as well? Then I can merge it.

Done, thank you

**Comment by Qendolin** [comment]
Thanks!

**Comment by Qendolin** [comment]
Published https://modrinth.com/mod/better-clouds/version/1.7.1+1.21-r

**Pull request merged**
